### PR TITLE
Uses lower-case extensions for Aah preview image

### LINKED ISSUE #3892: [Bug]: Error on theme select
### Describe the Bug

Error on selecting theme Aah
Looks like sample images are missing
Theme loads fine on reboot

### To Reproduce

Got to preferences,
Themes,
Select Aah 

### Expected Behaviour

Change of preview image

### Screenshots

java.lang.NullPointerException: Cannot invoke "java.net.URL.toString()" because "<parameter2>" is null
	at java.desktop/sun.awt.SunToolkit.getImageFromHash(Unknown Source)
	at java.desktop/sun.awt.SunToolkit.getImage(Unknown Source)
	at java.desktop/javax.swing.ImageIcon.<init>(Unknown Source)
	at net.rptools.maptool.client.ui.theme.ThemeSupport.getExampleImageIcon(ThemeSupport.java:648)
	at net.rptools.maptool.client.ui.preferencesdialog.PreferencesDialog.lambda$setInitialState$75(PreferencesDialog.java:1219)
	at java.desktop/javax.swing.JList.fireSelectionValueChanged(Unknown Source)
	at java.desktop/javax.swing.JList$ListSelectionHandler.valueChanged(Unknown Source)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
	at java.desktop/javax.swing.DefaultListSelectionModel.setValueIsAdjusting(Unknown Source)
	at java.desktop/javax.swing.JList.setValueIsAdjusting(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicListUI$Handler.mouseReleased(Unknown Source)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:54)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport.enter(Unknown Source)
	at java.desktop/java.awt.Dialog.show(Unknown Source)
	at java.desktop/java.awt.Component.show(Unknown Source)
	at java.desktop/java.awt.Component.setVisible(Unknown Source)
	at java.desktop/java.awt.Window.setVisible(Unknown Source)
	at java.desktop/java.awt.Dialog.setVisible(Unknown Source)
	at net.rptools.maptool.client.ui.preferencesdialog.PreferencesDialog.setVisible(PreferencesDialog.java:1045)
	at net.rptools.maptool.client.AppActions$15.executeAction(AppActions.java:670)
	at net.rptools.maptool.client.AppActions$ClientAction.execute(AppActions.java:3409)
	at net.rptools.maptool.client.AppActions$ClientAction.actionPerformed(AppActions.java:3441)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton.doClick(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:54)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

### MapTool Info

1.13.beta 1

### Desktop

win10

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by emmebi**
### Identify the Bug or Feature request

Fixes #3892

### Description of the Change

The preview files for Aah theme had a `PNG` filename extension, but were referred as `png` in the code; this change renames the filename name extensions to `png` for consistency with all the other images already in the package.

The change also adds some logs around the retrieval of the image, and the usage of an empty ImageIcon in case the preview can't be loaded.

### Possible Drawbacks

The performance loss caused by the logs should be negligible, as this happens only when retrieving the theme.

The usage of an empty ImageIcon prevents a traceback to reach the customer, but could hide the problem (i.e. the fact that the names of the preview files are wrong). This risk is mitigated however by the fact that the condition is correctly logged in the files.

### Documentation Notes

Note that the problem doesn't manifest itself when developing on Windows, because the resource is accessed via a file system path, which are case-insensitive under Windows.

### Release Notes

- Fixes an issue where theme selection dialog could show a traceback

- - -
This change is [Reviewable](https://reviewable.io/reviews/RPTools/maptool/3909)

### CODE REVIEW

File: src/main/java/net/rptools/maptool/client/ui/theme/ThemeSupport.java [hunk 1]
```diff
@@ -643,10 +643,16 @@ public static ImageIcon getExampleImageIcon(String themeName, Dimension dimensio
...
+      if (imageURL == null) {
+        log.warn(
+            "Failed to retrieve resource for theme name={} from url={}, using empty ImageIcon");
+        return new ImageIcon();
+      }
       var imageIcon =
-          new ImageIcon(
-              ThemeSupport.class.getResource(IMAGE_PATH + themeDetails.imagePath),
-              themeDetails.name);
+          new ImageIcon(ThemeSupport.class.getResource(imageLocation), themeDetails.name);
```
Comment (kwvanderlinde) [inline src/main/java/net/rptools/maptool/client/ui/theme/ThemeSupport.java:655]: We can use `imageURL` here as well for a bit more clarity.

Comment (emmebi) [reply src/main/java/net/rptools/maptool/client/ui/theme/ThemeSupport.java]: Thanks for pointing this out, I actually wanted to do that!

**Review by kwvanderlinde — APPROVED** [review]
