### PR TITLE
Generic dialog fixes

### LINKED ISSUE #4107: [Feature]: Limit dialogue boxes to screen boundaries
### Describe the Problem

Dialogue boxes can exceed the size of the screen, this usually pushes the Okay/Cancel buttons off the screen (see example below).
1. Editing content changes the controls focus so Enter/Escape may not function to close the dialogue.
2. Most users do not know how to move them (when they can be moved) to make the buttons visible. 
3. Acessibility measures like large-print make this more common, making it harder for those who need the most assistance.
### The Solution you'd like

Limit the max-height/width to the screen bounds and Insert a scroll pane to hold the content.

### Alternatives that you've considered.

Re-education camps

### Additional Context

image

### LINKED ISSUE #5423: [Bug]: Stray maximize button in some dialogs
### Describe the Bug

Since 1.16, some dialogs have maximize/restore buttons added to them. On Windows, these are in the titlebar as expected, but on Linux they overlap with the dialog content.

This affects the **New Token** dialog, **Edit Token** dialog, **Add Resource to Library...** dialog, and probably a few others.

### To Reproduce

1. Open MapTool on Linux running X11
2. Open Preferences, and enable **Show Dialog on New Token**.
3. Drag a token from the Library to the map. The **New Token** dialog should open.
4. Notice the maximize button overlapping the **Name** field.

### Expected Behaviour

The maximize button should be part of the titlebar, or else not be there.

### Screenshots

Here is the **New Token** dialog. Notice the square in the Name field - that's the maximize button.
Image

For the **Edit Token** dialog it's less intrusive since it normally doesn't overlap controls, but it can if the dialog is resized horizontally:
Image

### MapTool Info

1.16.2, latest develop (eeddfa5f40)

### Desktop

Linux Mint 22.1

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by bubblobill**
### Identify the Bug or Feature request
fixes #4107, #5376, #5423
advances #5147 
### Description of the Change
Maximise button removed
Changes to force fit dialog on available screen-space.

### Possible Drawbacks
Things work differently for different people.
Reduced accessibility.

### Documentation Notes
General dialog improvements to prevent them exceeding screen size.

### Release Notes
General dialog fixes.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RPTools/maptool/5432)

### CODE REVIEW

**Comment by bubblobill** [comment]
@kwvanderlinde 
It isn't perfect yet, but it puts us back in a good starting position.
Main problem is it doesn't quite do layout correctly for sizing some smaller dialogs, i.e. The scroll-pane shows a scroll-bar when there is ample space to expand. I was mostly concerned with fixing the oversize going off the screen issue.

File: src/main/java/net/rptools/maptool/client/swing/SwingUtil.java [hunk 1]
```diff
@@ -129,12 +117,48 @@ public static boolean isShiftDown(int modifiers) {
...
+    // how big can it be?
+    GraphicsConfiguration gc = outerWindow.getGraphicsConfiguration();
+    Insets insets = outerWindow.getToolkit().getScreenInsets(gc);
+    Rectangle bounds = gc.getDevice().getDefaultConfiguration().getBounds();
+    System.out.println(bounds);
+    System.out.println(insets);
+    bounds =
+        new Rectangle(
+            insets.left,
+            insets.top,
```
Comment (kwvanderlinde) [inline src/main/java/net/rptools/maptool/client/swing/SwingUtil.java]: It's not used, but for future sanity this should be `bounds.x + insets.left` and `bounds.y + insets.top`.

File: src/main/java/net/rptools/maptool/client/swing/SwingUtil.java [hunk 2]
```diff
@@ -129,12 +117,48 @@ public static boolean isShiftDown(int modifiers) {
...
+    }
+    // centre it
     int x = outerWindow.getLocation().x + (outerSize.width - innerSize.width) / 2;
     int y = outerWindow.getLocation().y + (outerSize.height - innerSize.height) / 2;
 
+    // just to make sure it doesn't cover UI elements
+    x = Math.max(x, insets.left);
+    y = Math.max(y, insets.top);
+    x =
+        x + innerSize.width > insets.left + bounds.width
```
Comment (kwvanderlinde) [inline src/main/java/net/rptools/maptool/client/swing/SwingUtil.java]: This condition isn't correct. `x` is the position on screen, not relative to `outerWindow`. You need something like
```
x - outerWindow.getLocation().x > insets.left + bounds.width
```

Otherwise, completely well-sized dialogs get thrown way out to the left unless the MT window is at (0, 0).

File: src/main/java/net/rptools/maptool/client/swing/SwingUtil.java [hunk 3]
```diff
@@ -129,12 +117,48 @@ public static boolean isShiftDown(int modifiers) {
...
+            ? insets.left + bounds.width - x + innerSize.width
```
Comment (kwvanderlinde) [inline src/main/java/net/rptools/maptool/client/swing/SwingUtil.java]: I'm not sure what is meant to be done here in practical terms. But `x` is a position, so it certainly shouldn't be subtracted except from another position. Since `x` can be very large (multiple monitors), this often gives a negative result, i.e., it tries to throw the dialog off the left side of the screen.

File: src/main/java/net/rptools/maptool/client/swing/SwingUtil.java [hunk 4]
```diff
@@ -129,12 +117,48 @@ public static boolean isShiftDown(int modifiers) {
    * @param outerWindow window to be centered over
    */
   public static void centerOver(Window innerWindow, Window outerWindow) {
+    // how big can it be?
+    GraphicsConfiguration gc = outerWindow.getGraphicsConfiguration();
+    Insets insets = outerWindow.getToolkit().getScreenInsets(gc);
+    Rectangle bounds = gc.getDevice().getDefaultConfiguration().getBounds();
+    System.out.println(bounds);
```
Comment (kwvanderlinde) [inline src/main/java/net/rptools/maptool/client/swing/SwingUtil.java]: Please remove the println logging.

File: src/main/java/net/rptools/maptool/client/swing/GenericDialog.java [hunk 5]
```diff
@@ -96,6 +71,44 @@ public void closeDialog() {
...
+    GraphicsConfiguration gc = getOwner().getGraphicsConfiguration();
+    Insets insets = getOwner().getToolkit().getScreenInsets(gc);
+    Rectangle bounds = gc.getDevice().getDefaultConfiguration().getBounds();
+    return new Dimension(
+        bounds.width - insets.left - insets.right, bounds.height - insets.top - insets.bottom);
+  }
+
+  @Override
+  public Dimension getPreferredSize() {
+    Dimension contentPref = getContentPane().getPreferredSize();
```
Comment (kwvanderlinde) [inline src/main/java/net/rptools/maptool/client/swing/GenericDialog.java]: I believe this should use `super.getPreferredSize()` otherwise it doesn't account for the titlebar. And that means I have to scroll to see the OK and Cancel buttons even for dialogs that have lots of space and so shouldn't need to scroll.

File: src/main/java/net/rptools/maptool/client/swing/GenericDialog.java [hunk 6]
```diff
@@ -96,6 +71,44 @@ public void closeDialog() {
...
+    System.out.println(getContentPane().getInsets());
+    System.out.println(contentPref);
```
Comment (kwvanderlinde) [inline src/main/java/net/rptools/maptool/client/swing/GenericDialog.java]: Remove the printlns

**Review by kwvanderlinde — CHANGES_REQUESTED** [review]

File: src/main/java/net/rptools/maptool/client/swing/SwingUtil.java (hunk 4 above)
Comment (bubblobill) [reply src/main/java/net/rptools/maptool/client/swing/SwingUtil.java]: Ahh... whoops

File: src/main/java/net/rptools/maptool/client/swing/GenericDialog.java (hunk 5 above)
Comment (bubblobill) [reply src/main/java/net/rptools/maptool/client/swing/GenericDialog.java]: It was, then it wasn't, now it is again.

File: src/main/java/net/rptools/maptool/client/swing/SwingUtil.java (hunk 3 above)
Comment (bubblobill) [reply src/main/java/net/rptools/maptool/client/swing/SwingUtil.java]: Oh yes it should be. If that position pushes the part off the window off screen it needs a thwacking.

File: src/main/java/net/rptools/maptool/client/swing/SwingUtil.java (hunk 2 above)
Comment (bubblobill) [reply src/main/java/net/rptools/maptool/client/swing/SwingUtil.java]: It is, but it makes no sense. I rewrote it to make more sense.

File: src/main/java/net/rptools/maptool/client/swing/SwingUtil.java [hunk 7]
```diff
@@ -129,12 +117,49 @@ public static boolean isShiftDown(int modifiers) {
...
     int y = outerWindow.getLocation().y + (outerSize.height - innerSize.height) / 2;
 
+    // just to make sure it doesn't cover UI elements, i.e. encroach on Screen Insets
+    // Left-hand side
+    x = (int) Math.max(x, usableScreenArea.getMinX());
+    // top side
+    y = (int) Math.max(y, usableScreenArea.getMinY());
+    // Right-hand side
+    if (x + innerSize.width > usableScreenArea.getMaxX()) {
+      x = (int) (usableScreenArea.getMaxX() - innerSize.width - x);
```
Comment (kwvanderlinde) [inline src/main/java/net/rptools/maptool/client/swing/SwingUtil.java]: This calculation always gives a negative result.

Instead, place the dialog so that its right edge matches the right edge of the screen:
```java
x = (int) usableScreenArea.getMaxX() - innerSize.width;
```

File: src/main/java/net/rptools/maptool/client/swing/SwingUtil.java [hunk 8]
```diff
@@ -129,12 +117,49 @@ public static boolean isShiftDown(int modifiers) {
...
+    Insets insets = outerWindow.getToolkit().getScreenInsets(gc);
+    Rectangle usableScreenArea = gc.getDevice().getDefaultConfiguration().getBounds();
+    usableScreenArea =
+        new Rectangle(
+            usableScreenArea.x + insets.left,
+            usableScreenArea.y + insets.top,
+            usableScreenArea.width - insets.left - insets.right,
+            usableScreenArea.height - insets.top - insets.bottom);
+
+    Dimension maxSize = usableScreenArea.getSize();
```
Comment (kwvanderlinde) [inline src/main/java/net/rptools/maptool/client/swing/SwingUtil.java:132]: Can use `usableScreenArea` everywhere instead of `maxSize` (one less thing to keep track of).

File: src/main/java/net/rptools/maptool/client/swing/SwingUtil.java [hunk 9]
```diff
@@ -129,12 +117,49 @@ public static boolean isShiftDown(int modifiers) {
    * @param outerWindow window to be centered over
    */
   public static void centerOver(Window innerWindow, Window outerWindow) {
+    // how big can it be?
+    // screen area minus OS bits like taskbars
+    GraphicsConfiguration gc = outerWindow.getGraphicsConfiguration();
+    Insets insets = outerWindow.getToolkit().getScreenInsets(gc);
+    Rectangle usableScreenArea = gc.getDevice().getDefaultConfiguration().getBounds();
```
Comment (kwvanderlinde) [inline src/main/java/net/rptools/maptool/client/swing/SwingUtil.java:124]: I don't have a good alternative, but I just wanted to call out the downsides of using the screen bounds here. The `usableScreenArea` isn't really be the available screen space, it is the bounds of the particular screen that the `outerWindow` (MT frame) happens to count as its current monitor.

This has two downsides:
1. It's an ambiguous concept if MT is spread over more than one monitor.
2. Even if there's lots of room for the dialog, the below checks might think it is out of space in one direction or another if the edge of the screen happens to be nearby.

As I said, I don't have an alternative, nor do I think it is worth trying to avoid these relatively minor issues.

**Review by kwvanderlinde — CHANGES_REQUESTED** [review]

File: src/main/java/net/rptools/maptool/client/swing/SwingUtil.java (hunk 9 above)
Comment (bubblobill) [reply src/main/java/net/rptools/maptool/client/swing/SwingUtil.java:124]: Lowest common denominator. This is a Dialogue Box. As such it needs to meet the expectations of the paradigm as well as a whole bunch of design guidelines that are hard to find. 

- This is part of `centerOver` so the dialogue is spawned with the intention of an obvious contextual relationship with the outer window. Usually achieved by being as close as possible to being in the middle of the owner, but.,,
- A dialogue should never cross a hard screen device boundary on creation. If the owner spans multiple devices then you just have to go with whichever ones you're given.
- The whole of the content of the dialogue should be visible. Where this is not possible,
- The whole of the content must be accessible.

In the past, MT has managed to spawn dialogue windows with title bars off the top of the screen, and the button bar off the bottom of the screen leaving users buggered. That is why I started this whole debacle, when I discovered that operating systems do not allow dialog boxes to be resizable, by design. This means they have no minimize/maximise functionality so you can't just use a key combination to fit it on the monitor. You need to rediscover how to move windows using cursor keys which is a pretty big ask for most users.

TBH, the solution to your problem is pretty easy. You just need to solve the concurrency problems with keeping the token editor open and we can stick it in an actual window that remembers its location in logical screen space.

File: src/main/java/net/rptools/maptool/client/swing/SwingUtil.java (hunk 7 above)
Comment (bubblobill) [reply src/main/java/net/rptools/maptool/client/swing/SwingUtil.java]: ja, done

File: src/main/java/net/rptools/maptool/client/swing/SwingUtil.java (hunk 8 above)
Comment (bubblobill) [reply src/main/java/net/rptools/maptool/client/swing/SwingUtil.java:132]: No. This is a case of the maths teacher telling you to show your working.
It's why I rewrote the whole thing with big long variable names and stuff so that it is obvious what is happening. Yes, it is functionally pointless, but it says `maxSize` which is hard to misconstrue.

File: src/main/java/net/rptools/maptool/client/swing/SwingUtil.java (hunk 9 above)
Comment (kwvanderlinde) [reply src/main/java/net/rptools/maptool/client/swing/SwingUtil.java:124]: > TBH, the solution to your problem is pretty easy. You just need to solve the concurrency problems with keeping the token editor open and we can stick it in an actual window that remembers its location in logical screen space.

I'll get right on that 😅 Definitely the long-term answer.

**Review by kwvanderlinde — APPROVED** [review]
