### PR TITLE
Fix #523 cheat exploit

### LINKED ISSUE #523: Cheating exploit
**Describe the bug**
The following can be used to emulate  « and »:

&#171
&#187
&laquo
&raquo
&#xAB
&#xBB

Thanks to aliasmask for identifying the two last symbols.

**To Reproduce**
Type any of the symbols above in the chat window.

**Expected behavior**
The symbols  « and » are not displayed, and instead the usual cheating message is sent ("Cheater. You have been reported".)

**MapTool Info**
- Version: 1.5.3
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

### PR DESCRIPTION
**Pull request by Merudo**
MT allows you to not use ; for the entities, so remove it from cheating symbols. Also, include &#xAB and &#xBB as cheating symbols.

Thanks to aliasmask for identifying the two new symbols.

---
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/521)

### CODE REVIEW

**Comment by Merudo** [comment]
Thanks to aliasmask for identifying the two new symbols.

**Comment by Phergus** [comment]
Don't see an issue filed for this.

**Comment by Merudo** [comment]
I opened issue #523

File: src/main/java/net/rptools/maptool/client/ui/commandpanel/CommandPanel.java [hunk 1]
```diff
@@ -441,7 +441,7 @@ public void keyReleased(KeyEvent kre) {
    * FIXME: this is insufficient for stopping faked rolls; the user can still do something like &{"laquo;"}.
    */
   public static final Pattern CHEATER_PATTERN =
-      Pattern.compile("\u00AB|\u00BB|&#171;|&#187;|&laquo;|&raquo;|\036|\037");
+      Pattern.compile("\u00AB|\u00BB|&#171|&#187|&laquo|&raquo|\036|\037|&#xAB|&#xBB");
```
Comment (kayila) [inline src/main/java/net/rptools/maptool/client/ui/commandpanel/CommandPanel.java]: Could you please re-add the semicolons, but add a question mark after them so they become optional?
```suggestion
      Pattern.compile("\u00AB|\u00BB|&#171;?|&#187;?|&laquo;?|&raquo;?|\036|\037|&#xAB|&#xBB");
```

Comment (Merudo) [reply src/main/java/net/rptools/maptool/client/ui/commandpanel/CommandPanel.java]: Sure. I also added the ;? to &#xAB and &#xBB.
