### PR TITLE
Minor json code clean up and trapping when function isnt defined

### LINKED ISSUE #1206: JSON macro functions will behave incorrectly if function is not found
**Describe the bug**
The json function code returns null if the function is not found. This should throw an exception with a valid error message. Currently neither of these will occur but the exception should be put in place to catch any problems with future edits.

### PR DESCRIPTION
**Pull request by cwisniew**
fixes #1206

---
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/1207)

### CODE REVIEW

**Comment by Merudo** [comment]
Could the error message be localized via I18N (`macro.function.general.unknownFunction`)?

File: src/main/java/net/rptools/maptool/client/functions/json/JSONMacroFunctions.java [hunk 1]
```diff
@@ -518,8 +518,7 @@ public Object childEvaluate(Parser parser, String functionName, List<Object> arg
           }
         }
     }
-
-    return null; // TODO CDW
+    throw new ParserException(functionName + "(): Unknown function");
```
Comment (Merudo) [inline src/main/java/net/rptools/maptool/client/functions/json/JSONMacroFunctions.java]:
```suggestion
    throw new ParserException(I18N.getText("macro.function.general.unknownFunction", functionName));
```
