### PR TITLE
Fix handlebars url fetch

### LINKED ISSUE #5806: [Bug]: Loading Handlebars Partial templates by URL is broken
### Describe the Bug

The Java bridge glue is injected at URL fetch time to support injecting the glue into navigated-to pages.
The detection of which fetches to inject the glue into is based on file mime type detection, but handlebars doesn't have a registered mime type and get returned as HTML, so has glue injected that are invalid handlebars.

### To Reproduce

Use the AddOn in https://gitlab.com/richardmaw/maptool-bar-test/ with the properties and set a token to the Bars stat sheet.

Observe no stat sheet is rendered and the console logs an exception.

### Expected Behaviour

Stat sheet renders.

### Screenshots

_No response_

### MapTool Info

develop

### Desktop

_No response_

### Additional Context

Likely broken since https://github.com/RPTools/maptool/pull/5461, https://github.com/RPTools/maptool/pull/5489 fixed other types of file.

### PR DESCRIPTION
**Pull request by fishface60**
### Requirements for Contributing a Bug Fix or Enhancement
* Fill out the template below. Any pull request that does not include enough information to be reviewed in timely manner will result in a request for you to update the pull request 
  and possibly closure of the pull request if it is not provided after this request.
* After you create the pull request, all status checks must pass before a maintainer will review your contribution. 

### Identify the Bug or Feature request

Fixes https://github.com/RPTools/maptool/issues/5806

### Description of the Change

This passes the file path to file type deduction in more places

### Possible Drawbacks

There may be valid handlebars partial templates that don't appear to be html and wouldn't get returned as Type.HANDLEBARS.

### Release Notes

* Fixed handlebars partial template loading for stat sheets and potential fetching of .hbs files from WebViews.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RPTools/maptool/5807)

### CODE REVIEW

File: src/main/java/net/rptools/maptool/util/HandlebarsUtil.java [hunk 1]
```diff
@@ -45,6 +45,12 @@
  * @param <T> The type of the bean to apply the template to.
  */
 public class HandlebarsUtil<T> {
+  public static boolean isAssetFileHandlebars(String filename) {
+    if (filename == null) {
+      return false;
+    }
+    return filename.endsWith(".hbs");
+  }
```
Comment (cwisniew) [inline src/main/java/net/rptools/maptool/util/HandlebarsUtil.java:60]: This should be case-insensitive

**Review by cwisniew — CHANGES_REQUESTED** [review]

File: src/main/java/net/rptools/maptool/util/HandlebarsUtil.java (hunk 1 above)
Comment (fishface60) [reply src/main/java/net/rptools/maptool/util/HandlebarsUtil.java:60]: Thanks, amended.

Comment (cwisniew) [reply src/main/java/net/rptools/maptool/util/HandlebarsUtil.java:60]: Thanks!

**Review by cwisniew — APPROVED** [review]
