### PR TITLE
Fix incorrect macroprop "toolapplyToSelected"

### LINKED ISSUE #1874: getMacroProps returns misnamed property "toolapplyToSelected"
**Describe the bug**
The json returned by `getMacroProps` returns the property `toolapplyToSelected`.

The property name should be `applyToSelected` instead.

**To Reproduce**
1. Use `getMacroProps` on a macro.
2. Notice the included property `toolapplyToSelected` and the missing `appyToSelected`

**Expected behavior**

The property is named  `appyToSelected`

**MapTool Info**
- Version: 1.7.0
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

### PR DESCRIPTION
**Pull request by Merudo**
- Fix getMacroProps returning properties with "toolapplyToSelected" and "tooltooltip" instead of "applyToSelected" and "tooltip"
- Fix #1874

---
This change is [Reviewable](https://reviewable.io/reviews/rptools/maptool/1875)

### CODE REVIEW

File: src/main/java/net/rptools/maptool/client/functions/MacroFunctions.java [hunk 1]
```diff
@@ -175,7 +175,7 @@ public Object getMacroButtonProps(Token token, int index, String delim) throws P
       } else {
         props.addProperty("tooltooltip", "");
```
Comment (selquest) [inline src/main/java/net/rptools/maptool/client/functions/MacroFunctions.java:176]: Looks like this will also create a bad property name "tooltooltip" in cases of missing tooltip.

Comment (Merudo) [reply src/main/java/net/rptools/maptool/client/functions/MacroFunctions.java:176]: Good catch!

**Comment by Phergus** [comment]
@selquest   You have a blocking comment that needs resolution.

**Comment by Merudo** [comment]
I'm sorry@selquest - I didn't mean to dismiss you from the discussion, I was just trying to mark your comment as resolved since I did implement your very helpful suggestion :).

**Comment by selquest** [comment]
Ahh, sorry - didn't realize I was holding things up with that.  No worries!
