### PR TITLE
Fix for cancelling from map export

### LINKED ISSUE #4324: [Bug]: Map-Export Map- can't cancel
### Describe the Bug

If you attempt to export a map, you can't cancel out of the menu and are forced to save the file.
You can choose to overwrite a file and will be prompted cancel after you've selected save

### To Reproduce

Click Map
Select Export Map

Click cancel

### Expected Behaviour

Clicking cancel will close the dialog

### Screenshots

na

### MapTool Info

v1.14.0rc2

### Desktop

Win11, Ubuntu 23.04

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Jmr3366**
### Identify the Bug or Feature request
Fixes #4324 

### Description of the Change

Break out of loop when map export is cancelled.

Update of PR #4325 with advice from thelsing.

### Possible Drawbacks

None

### Documentation Notes

N/A

### Release Notes

N/A

- - -
This change is [Reviewable](https://reviewable.io/reviews/RPTools/maptool/4327)

### CODE REVIEW

File: src/main/java/net/rptools/maptool/client/AppActions.java [hunk 1]
```diff
@@ -2848,27 +2848,26 @@ protected void executeAction() {
...
-              } else {
-                tryAgain = false;
-                try {
-                  mapFile = getFileWithExtension(mapFile, AppConstants.MAP_FILE_EXTENSION);
-                  if (mapFile.exists()) {
-                    if (!MapTool.confirm("msg.confirm.fileExists")) {
-                      return;
-                    }
+            if (chooser.showSaveDialog(MapTool.getFrame()) != JFileChooser.APPROVE_OPTION) break;
+            File mapFile = chooser.getSelectedFile();
```
Comment (cwisniew) [inline src/main/java/net/rptools/maptool/client/AppActions.java]: The break statement in the if should be in { } to match coding standards

**Review by cwisniew — CHANGES_REQUESTED** [review]

**Review by kwvanderlinde — APPROVED** [review]

**Review by cwisniew — APPROVED** [review]
