### PR TITLE
JS API setProperty() fix.

### LINKED ISSUE #4237: [Bug]: changes via javascript token.setProperty is not propagated to clients
### Describe the Bug

I am setting a property on a token while the server is running and a client is connected via a javascript-UDF. The property is set on server side correctly, impersonating the token and calling `[getProperty("test")]` returns "newValue". But on the client it returns whatever old value it had before.

### To Reproduce

1) Create the following two macros on a "Lib:js" Token, with URL access enabled:
setTest macro on Lib:js:
```
"use strict";
function setTest(tokenId) {
	let token = MapTool.tokens.getTokenByID(tokenId);
	token.setProperty("test", "newValue");
}

MTScript.registerMacro("setTest", setTest);

```

init macro on Lib:js: 
```
[h: js.createNS("jsFunctions")]
[h: js.evalURI("jsFunctions", "lib://js/macro/setTest?cachelib=false")]
```

2) Click on the init Button on Lib:js to register the setTest javascript-UDF.
3) impersonate a TestToken on the server and call `[setProperty("test", "oldValue")]`. Impersonate the same TestToken on the client. Now `[getProperty("test")]` called on server and on client returns "oldValue" in both cases, as expected.
4) call on the server `[js.setTest(currentToken())]`. 
5) call `[getProperty("test")]` on the server returns "newValue" (correct), a call to `[getProperty("test")]` on the client returns "oldValue", which is the bug.

**Additional Info:**
Writing the javascript as a workaround like this, i.e. calling a macro for setting the property, works as expected:

```
"use strict";
function setTest(tokenId) {
    let token = MapTool.tokens.getTokenByID(tokenId);
    MTScript.setVariable("value", "newValue");
    MTScript.setVariable("tokenId", tokenId);
    MTScript.evalMacro("[h: setProperty('test', value, tokenId)]");
}
```

**Hint from Azhrei on in the discord channel:**
Inside the Java code, changing a token property requires calling zone.putToken(token) on the token.  It may be that the MapTool.tokens API in JS doesn't automatically do that — I don't know, just offering up ideas.

### Expected Behaviour

Token property changes in javascript on the server should be propagated to the clients, i.e. in step 5 `[getProperty("test")]` should return "newValue" on server and client.

### Screenshots

_No response_

### MapTool Info

Version 1.13.2, New Install, Gentoo Linux using the debian package.

### Desktop

Gentoo Linux: Linux omikron 6.1.41-gentoo #1 SMP Tue Jul 25 19:39:42 CEST 2023 x86_64 Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz GenuineIntel GNU/Linux

### Additional Context

==== MapTool Information ====
MapTool Version: 1.13.2
MapTool Home...: /home/stephan/.maptool-rptools
MapTool Install: /home/stephan/Anwendungen/maptool_1.13.2-amd64/data/opt/maptool/lib/app
Max mem avail..: 15 GB
Max mem used...: 560 MB
Custom Property: -DMAPTOOL_LOGDIR=/home/stephan/.maptool-rptools/logs
Custom Property: -DMAPTOOL_DATADIR=.maptool-rptools

==== Java Information ====
Java Home......: /home/stephan/Anwendungen/maptool_1.13.2-amd64/data/opt/maptool/lib/runtime
Java Vendor....: Eclipse Adoptium
Java Version...: 17.0.1
Java Parameters: 
  -Djpackage.app-version=1.0
  -Xss8M
  -Dsun.java2d.d3d=false
  -Dsentry.environment=Production
  -Dfile.encoding=UTF-8
  -Dpolyglot.engine.WarnInterpreterOnly=false
  -XX:+ShowCodeDetailsInExceptionMessages
  --add-opens=java.desktop/java.awt=ALL-UNNAMED
  --add-opens=java.desktop/java.awt.geom=ALL-UNNAMED
  --add-opens=java.desktop/sun.awt.geom=ALL-UNNAMED
  --add-opens=java.base/java.util=ALL-UNNAMED
  --add-opens=javafx.web/javafx.scene.web=ALL-UNNAMED
  --add-opens=javafx.web/com.sun.webkit=ALL-UNNAMED
  --add-opens=javafx.web/com.sun.webkit.dom=ALL-UNNAMED
  --add-opens=java.desktop/javax.swing=ALL-UNNAMED
  --add-opens=java.desktop/sun.awt.shell=ALL-UNNAMED
  --add-opens=java.desktop/com.sun.java.swing.plaf.windows=ALL-UNNAMED
  -Djpackage.app-path=/home/stephan/Anwendungen/maptool_1.13.2-amd64/data/opt/maptool/bin/MapTool

==== OS Information ====
OS Name........: Linux
OS Version.....: 6.1.41-gentoo
OS Architecture: amd64
PATH...........: /usr/local/sbin:/usr/local/bin:/usr/bin:/opt/bin:/usr/lib/llvm/16/bin:/usr/lib/llvm/15/bin:/opt/cuda/bin
Number of Procs: 12

==== User Information ====
User Name: stephan
User Home: /home/stephan
User Dir.: /home/stephan/Anwendungen/maptool_1.13.2-amd64/data/opt/maptool/bin

==== Network Interfaces ====
Display Name..: eno1
Interface Name: eno1
Address...: 192.168.14.6

Display Name..: lo
Interface Name: lo
Address...: 127.0.0.1

Host Address...: 192.168.14.6
Default Gateway: 192.168.14.1

==== Locale Information ====
Country.: Germany
Language: German
Locale..: German (Germany)
Variant.: 

==== Encoding Information ====
Default Locale:   de_DE
Default Charset:  UTF-8
file.encoding:    UTF-8
sun.jnu.encoding: UTF-8
Default Encoding: UTF8

==== Display Information ====
Number of Displays: 3
Display 1: 5120x1080(-1)
Display 2: 1280x1024(-1)
Display 3: 1920x1080(-1)

==== Internet Gateway Devices ====
	No IGDs Found!

### PR DESCRIPTION
**Pull request by ColdAnkles**
### Identify the Bug or Feature request
resolves #4237

### Description of the Change
Resolves the Server/Client inconsistency when server updates a token via one of the JS API `setName()`, `setNotes()`, or `setProperty()`.

### Possible Drawbacks
Needs some more testing, and commentary by someone who understands the client<->server communication better.

### Documentation Notes
Not much to really document - issue "how to reproduce" shows the problem fairly well - and now it shouldn't exist.

### Release Notes
- Fixed an issue where server token changes via JS `setName()`, `setNotes()`, or `setProperty()` didn't propagate to clients.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RPTools/maptool/4301)

### CODE REVIEW

File: src/main/java/net/rptools/maptool/client/script/javascript/api/JSAPIToken.java [hunk 1]
```diff
@@ -130,6 +134,9 @@ public void setProperty(String name, Object value) {
     String playerId = MapTool.getPlayer().getName();
     if (trusted || token.isOwner(playerId)) {
       this.token.setProperty(name, value.toString());
+      // this.map.putToken(this.token);
```
Comment (thelsing) [inline src/main/java/net/rptools/maptool/client/script/javascript/api/JSAPIToken.java]: This can be removed.

**Review by thelsing — APPROVED** [review]

File: src/main/java/net/rptools/maptool/client/script/javascript/api/JSAPIToken.java [hunk 2]
```diff
@@ -184,4 +191,14 @@ public boolean isOnCurrentMap() {
         MapTool.getFrame().getCurrentZoneRenderer().getZone().getToken(new GUID(this.getId()));
     return this.token == findToken;
   }
+
+  @HostAccess.Export
```
Comment (cwisniew) [inline src/main/java/net/rptools/maptool/client/script/javascript/api/JSAPIToken.java]: This shouldn't be exported as you don't want to make it available to scripts
